# print("hello world")
# s1 = "my name is khue"
# print(s1)
# print(s1.title())
# print(s1.upper())
# print(s1.lower())
# s2 = input()
# print(s2)
# name = input("Enter your name: ")
# print("Hello, " + name + "!")
# width = int(input())
# height = int(input())
# print(f"Dien tich  {width * height}")
# # s=input().split()
# # w = int(s[0])
# # h = int(s[1])
# # print(w*h)

a = int(input("cr"))
b = int(input("cd"))
print(a*b)